[[news]]
date = "2026-08"
content = "Completed my M.S. in Artificial Intelligence at GIST 🎓"

[[news]]
date = "2026-02"
content = "Won 1st Place, Track 1: Lightweights at the Orak Game Agent Challenge 2025 (hosted by KRAFTON AI) 🏆"

[[news]]
date = "2025-11"
content = "Won 2nd Place, Track 1: Battling (Gen 1) at the PokeAgent Challenge with Team 4thLesson 🥈"
