[[news]]
date = "2026-08"
content = "GIST 인공지능대학원 석사 과정을 마쳤습니다 🎓"

[[news]]
date = "2026-02"
content = "KRAFTON AI가 주최한 Orak Game Agent Challenge 2025 Track 1: Lightweights 부문에서 1위를 차지했습니다 🏆"

[[news]]
date = "2025-11"
content = "Team 4thLesson으로 참가한 PokeAgent Challenge Track 1: Battling (Gen 1) 부문에서 2위를 차지했습니다 🥈"
